Repository yeonod/NestJsBasic, pull requests merged in 2023-11, with the labels that each got.

#7 CRUD 게시판을 생성했습니다.
  .eslintrc.js
  docker-compose.yml
  package-lock.json
  package.json
  src/boards/board.model.ts
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/dto/create-board.dto.ts
  tsconfig.json
Labels: NestJS

#8 Pipe를 이용한 유효성 체크 기능을 추가했습니다.
  package-lock.json
  package.json
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/dto/create-board.dto.ts
  src/boards/pipes/board-status-validation.pipe.ts
Labels: Structure

#9 원활한 코드리뷰를 위해 pull request tempalte를 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, Convension
